### ISSUE TITLE
Add sponsor logos to website

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#1]
- [x] AKRA
- [x] Phraseapp
- [x] WLW
- [x] Railslove
- [x] sum.cumo
- [x] Shopify
- [x] Ioki
- [x] Ubilabs
- [x] SolarisBank
- [x] Epages
- [x] Toptranslation
- [x] OpenSUSE
- [x] 9Elements
- [x] Avocado Store
- [x] Megorei
- [x] Depfu

**Comment by halfbyte** [comment]
If you receive sponsor logos, either drop them into an issue at rughh/ruby-unconf-website or add the image directly to the [assets/images/sponsors](https://github.com/rughh/ruby-unconf-website/tree/master/assets/images/sponsors) folder there and ping the #website channel on slack.
