### ISSUE TITLE
Volunteers / Helpers

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#12]

**Comment by p0wl** [comment]
We need:

* entrance 4
* wardrobe 2
* speaker support / technical support 2
* schedule support 1
* cleanup 2

approx 4-5 non orga team (non camera/photo) helpers

**Comment by p0wl** [comment]
candidates:

- Gerrit (study.eu, nur Samstag)
- Klaudia
- Ole (registration, ..., has a ticket)
- ~Johanna Frank (TT)~
- ~Milena Junker (TT)~
- Annkatrin Rosenbruch (TT)
- Sarah Hillje (TT)
- Nicky S
- Denis Zalessky

**Comment by p0wl** [comment]
will write an email to all volunteers this weekend. topics:
* schedule
* "jobs"
* preferences (jobs, days)
* see talks y/n

**Comment by 9lindt** [comment]
I would like to help on Saturday

**Comment by p0wl** [comment]
Nice! can you shoot me your name and email at paulmoelders@gmail.com? thanks!
