### ISSUE TITLE
Promote Unconf in Ruby Usergroup Berlin

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#16]
@janz93

Next meeting is on the 5th of april.

**Comment by janz93** [comment]
I was talking with Tobias.
Tobias said that @phoet contacted him already and Tobias made so promotion on the last meetup already for us.
Because of that should I still go the april meeting in person to promote the ruby unconf?
@halfbyte @lindtdev any thoughts?

**Comment by phoet** [comment]
the reaction to tobi after the rugb meetup was close to zero in terms of ticket sales, so i think it would make sense to give it another try

**Comment by janz93** [comment]
Okay thanks @phoet.

**Comment by janz93** [comment]
Have the go to promote the ruby uncunf at the Berlin meetup in April
