### ISSUE TITLE
Search for photos by kiezastronaut for website

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#18]
@halfbyte and @p0wl can search for photos

@sr189 will contact kiezastronaut@gmail.com

https://www.instagram.com/kiezastronaut/?hl=de

**Comment by p0wl** [comment]
echt schöne fotos dabei, ich find die hier besonders schön und denke die kann man gut in die Webseite oder sonstiges Material einbauen

https://www.instagram.com/p/BfXuts9gYOY/?hl=de&taken-by=kiezastronaut
https://www.instagram.com/p/BfA1OqaAHpv/?hl=de&taken-by=kiezastronaut
https://www.instagram.com/p/BeSMFVXg7mS/?hl=de&taken-by=kiezastronaut
https://www.instagram.com/p/BXx_gqng51T/?hl=de&taken-by=kiezastronaut

**Comment by p0wl** [comment]
https://rubyunconf.slack.com/archives/C83PGDA8P/p1521537428000348

**Comment by p0wl** [comment]
i'll write him
