### ISSUE TITLE
Photograph

### ISSUE THREAD

**Issue by p0wl** [rughh/ruby-unconf#19]
Fr. Weichental offered to connect us with students that we can ask for help regarding photographs and video recording.

Todo:
* [x] ~write job description for photographer~
  * 2 days, photos of speakers, venue, visitors, ...
  * awareness for people who do not want to be visible in pictures
  * family pictures
  * equipment (HAW?)
* [x] write job description for video recording assistant
  * 2 days, 2 tracks (at least 2 people)
  * equipment (HAW?)
  * record all talks (if speaker is ok with it)
* Lageplan anfragen
* Freiwillige Helfer

**Comment by p0wl** [comment]
https://docs.google.com/document/d/1L6CREReIaA31XDJhmbDMWcv6KEjgW_KXcsVqPLpZBeg/edit

bitte einmal Review/verbessern @rughh/ruby-unconf-team

**Comment by p0wl** [comment]
We found a photographer, @fstehle will do photos on both days for us \o/.

If we want photos from the party, we need someone for that.

**Comment by p0wl** [comment]
Updated the document, please review @rughh/ruby-unconf-team

**Comment by fstehle** [comment]
@p0wl will you take care of a mechanism to tag people, who do not want to be visible in pictures?

**Comment by p0wl** [comment]
für party: photobooth von @halfbyte wird reanimiert \o/

**Comment by p0wl** [comment]
@fstehle we will probably get two lanyard colors to differentiate, very good point.

**Comment by p0wl** [comment]
fyi: black lanyards: photo ok, white lanyards: no photo
