### ISSUE TITLE
Beach Flags

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#20]

**Comment by sr189** [comment]
I searched for 3 flags: 2,50m, metalstand and waterbag, single sided print. I calculated 3 flags for the forum, the street near the canal and the finkenau street (Dietze Hörsaal). Double sided prints are roughly 50 EUR more expensive.

All prices incl. vat.

Beachflags.com:
https://www.beachflags.com/de/beachflag-flying-m.html
406 EUR + delivery, 7 to 12 days delivery 

Cewe:
https://www.cewe-print.de/beachflags-jetzt-bestellen.aspx
429,92 EUR incl. delivery - delivery until 16th of april.

https://www.bannerstop.com/produkte/fahnen-drucken/beachflag/beachflag-set-fortuna.html
460 EUR (153 for a single one):

**Comment by p0wl** [comment]
Hmm, I'd be okay with spending that money, because we need a marker as we know that the entrances are far from obvious. Banners could be cheaper, but will be much harder to install.

I'm fine with it, your call =)

**Comment by Farson** [comment]
Beachflags sind bestellt :heavy_check_mark:

**Comment by Farson** [comment]
Guten Tag Waldemar,

Vielen Dank für Ihre Bestellung und Datei(en).
Wir haben Ihre Entwurf überprüft, und die Qualität ist ok.
Anbei senden wir Ihnen unseren Bestätigung/Rechnung und das Layout der Beachflag.
Der Produktion wird gestartet, die Produktionszeit ist 7-11 Tage.
Wenn ihre Bestellung wird gesendet, Sie erhalten die T & T Nummer von UPS per E-Mail.
Sollten Sie weitere Fragen haben, stehen wir Ihnen gerne zur Verfügung
With kind regards / Met vriendelijke groet  / Mit freundlichen Grüssen / Cordialement,

**Comment by Farson** [comment]
sind angekommen :tada:
