### ISSUE TITLE
A4/A5 Handouts/Flyer

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#22]

**Comment by p0wl** [comment]
draft: https://rubyunconf.slack.com/files/U827U7ZJR/F9XMV3KC6/bildschirmfoto_2018-03-27_um_17.19.31.png

todo:
 * [ ] texts
 * [ ] design adjustments
 * [ ] printing? 20-30 Stück sollten locker reichen -> @halfbyte kennt jemanden mit nem Drucker
