### ISSUE TITLE
Ask Schanzenstern for updated quote

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#24]
The current quote is based on last years numbers. Schanzenstern wanted to create a new quote.

**Comment by phoet** [comment]
we already have an offer, it's in the drive https://drive.google.com/drive/folders/1Eztmdz8MdJgL9eVGEOABj5xecsDTjCnc

**Comment by p0wl** [comment]
did we order that new offer?

**Comment by phoet** [comment]
that is the basis for the catering. if we want something changed, we should tell that schanzenstern.

**Comment by phoet** [comment]
we will have to get in contact close to the event anyways to tell them real numbers and maybe order something for people with diets etc.
