### ISSUE TITLE
Cake  🍰

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#25]

**Comment by phoet** [comment]
no time to do that

**Comment by p0wl** [comment]
I'll take care. I'll try to grab @hendric at the serverless meetup tonight and ask for a contact to cafe schmidt and what they got for jeffconf.

**Comment by hendric** [comment]
@p0wl I can't make it tonight but just let me know what you need.

**Comment by p0wl** [comment]
FYI: Cafe Schmidt & Schmidtchen hat auf der JeffConf mit 1,5 Stücken Blechkuchen (3 Sorten glaub ich) pro Person gerechnet. Pro Person 4,5€. Beauftragung spätestens 2 Wochen vorher.
Ich fand den Kuchen sehr gut, aber ist halt "nur" Blechkuchen.

**Comment by p0wl** [comment]
wird beauftragt

**Comment by phoet** [comment]
dann bitte die Kosten entsprechend im Budget einreisen, hab da schon nen Platzhalter für Kuchen

**Comment by p0wl** [comment]
Kuchenteller?!

**Comment by p0wl** [comment]
vegan?
