### ISSUE TITLE
Coffee ☕️

### ISSUE THREAD

**Issue by halfbyte** [rughh/ruby-unconf#26]
@phoet said he did some brainstorming with @freetwix on what to do here, maybe they can fill us in?

Things that need to be done:

- [x] Find vendor, book them
- [ ] Print sponsor logo on cups if needed

**Comment by halfbyte** [comment]
@phoet (Initially assigning this to you to document current state of discussion, we can reassign if needed)

**Comment by phoet** [comment]
not much to document. we talked about AKRA providing mugs, i think that's it. someone needs to take this further and involve jochen.

**Comment by freetwix** [comment]
ola. i'm back from vacation. do you need any help here? what's with the costs of coffee vendor and mugs and mug-sponsor-printing?

**Comment by halfbyte** [comment]
@freetwix I'll try to get someone from the team onto this. Please hold the line.

**Comment by p0wl** [comment]
wish from a participant: "Vegetarian. If you're going to hire someone with a proper coffee machine (i.e. for paid coffee), it'd be absolutely amazing if they had almond milk with them ^_^" (just FYI)

**Comment by p0wl** [comment]
last year jsunconf: https://www.diecoffeecaterer.de/catering/ (see https://rubyunconf.slack.com/archives/C7NPWQKU1/p1521106437000488)

maybe ask https://www.el-rojito.de/ and https://www.publiccoffeeroasters.com/services/fuer-messen-events/ as well

**Comment by p0wl** [comment]
to be decided: who takes care/wants to take care of mug design and order? akra or we?

**Comment by freetwix** [comment]
we could do the job of collecting some design ideas, putting them to the vote here and look for vendors. 
* how many mugs? 
* what's the budget?
* any corporate design from the unconf to fullfill?

**Comment by alster-wasser** [comment]
Hey @freetwix! I am now assigned to this topic. 

Mugs meant plastic cups. I would guess we need at the very least 1000 plastic cups for the two days. More if the coffees are small. My guess would be that we need 3000: we have around 250 people (attendees and orga team, helpers etc), two days, plus there will be not only breakfast and lunch but also regular breaks between talks. 4 coffee cups per person per day seems a good guess.

I will get back to you about the budget soon. AKRA has agreed to be our coffee sponsor and I think they (you) already gave us the money so we need to decide how much of it we are spending on the cups and how much on the coffee / milk.

We don't have any requirements re: corporate design but it would be nice if you could include the logo from the website https://rubyunconf.eu/ (the coral ruby with the purple UNC/ONF letters). We assume you want to print your own logo on the cups.

We also need to choose the provider. Our favorite was El Rojito, but we have a few more candidates.

Once we've decided on the provider we'll see about the milk options.

**Comment by freetwix** [comment]
hey @lindtdev,

maybe we could ask the provider for suggestions to the mugs - i personally would not like to have plastic cups and would prefer some other material or even real mugs to be reused from the coffee crowd.
as with the logos - we will start to design some drafts and show them here.

**Comment by phoet** [comment]
as stated already: AKRA is _allowed_ to provide mugs. so if they would like to do promotion by putting their logo on something that people use or take with them, that's fine.

> so we need to decide how much of it we are spending on the cups and how much on the coffee / milk.

no, all the money goes toward the coffee-vendor and i guess that he will also bring it's own one-way cups.

**Comment by phoet** [comment]
and i agree with @freetwix it would be nice to not have plastic/one-way cups but something re-usable.

i think that we won't get around one-way stuff anyways as we do not have cleaning staff that could take care of cleaning up.

**Comment by freetwix** [comment]
ola @phoet ,

* the coffee provider is booked and choosen from the rubyunconf
* the coffee provider will bring one-way cups

As far as the coffee provider is choosen, AKRA would like to coordinate with the provider about the cups, one-way and probably also give-away cups, and the logo prints.

And AKRA will think about some other promotion like a banner et. all. at the coffee area if it is ok?

**Comment by halfbyte** [comment]
My 2c, as I spent some time researching this yesterday: 

- I think @lindtdev meant "plastic cups" as a placeholder for non-reusable. JSUnconf last year had the typical paper cups, printed by Flyeralarm (@freetwix We can provide details on that)
- Regarding Reusable cups, JSUnconf 2016 had (afaik) reusable cups that people were supposed to keep. Maybe @klyrr can provide info on the provider of these (they were made of biodegradable plastics of sorts and had a silicone cover) and how well that worked. I seem to remember seeing more and more people with paper cups on sunday. The procedure did not include washing by the coffee provider and I am not sure if that isn't already a violation of food regulations :)

**Comment by klyrr** [comment]
It worked good on Saturday but on Sunday not optimal because a lot of people forgot their cups at home.

We ordered these this year: https://www.giffits.de/eco-kaffeebecher-aus-bambusfaser-werbegeschenke-347096.htm

**Comment by freetwix** [comment]
hey,
we ordered 250 cups from the ones @klyrr mentioned above (thanks for the hint). red variant of the cups with printed akra logo.
is the coffee provider already choosen? any help needed on this topic?
greets, jochen

**Comment by alster-wasser** [comment]
I'll have a call with el rojito tomorrow to discuss this

**Comment by p0wl** [comment]
Waiting for response from el rojito if they can make it on our weekend

**Comment by p0wl** [comment]
What about tee? =) if not with coffee caterer, maybe with schanzenstern

**Comment by alster-wasser** [comment]
El rojito couldn't make it, coffee is now ordered from Die Coffee Caterer. They won't have tea.

**Comment by alster-wasser** [comment]
I was wrong about the tea! They'll bring some.
