### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#27]
- [x] speak to Jasper Holz from HAW
- [x] ~place hangout to find students~

**Comment by sr189** [comment]
Jasper and a friend of his would like to do the video recording themselves. Will talk to him later if he thinks we'll need a third person like we planned.

**Comment by p0wl** [comment]
f*cking awesome

**Comment by sr189** [comment]
Just had another telephone call with Jasper. He is fine with the 20 EUR / h and thinks 2 man are ok to handle both rooms. They have a small business (Kleingewerbe) and will send an invoice to the Boot eV.

He will now reserve the two cameras from the HAW, if that will run into problems he will let us know.

Since he is helping out at the Forum Finkenau as tutor we will see him on friday before the conference for the last consultations.
