### ISSUE TITLE
Keynote Speakers

### ISSUE THREAD

**Issue by p0wl** [rughh/ruby-unconf#30]
* ~Zed Shaw kann nicht~
* ~Zach Holman haben wir uns dagegen entschieden~
* ~Julia Evans: @lindtdev (über Twitter angefragt, noch keine Reaktion)~
* Tenderlove: @halfbyte hat angefragt, Agentin antwortet gerade nicht
* ~DHH: @p0wl hat angefragt, kann nicht~
* ~Matz: @sr189 hat angefragt, kann nicht~
* ~Sandi Metz: @lindtdev (angefragt, sie kann nicht)~
* ~Adam Stacoviak: @janz93 (angefragt)~
* ~Terence Lee: @halfbyte (angefragt)~
* ~Luca Guidi: @janz93  (https://github.com/jodosha) (abgesagt)~
* Steve Klabnik: @sr189 hat angefragt, steve antwortet nicht mehr

**Comment by halfbyte** [comment]
Tenderlove it is.
