### ISSUE TITLE
Lanyards / Badges

### ISSUE THREAD

**Issue by halfbyte** [rughh/ruby-unconf#32]
Lanyards, siehe hier: https://www.flyeralarm.com/de/shop/configurator/index/id/5883#3066=15999&3067=15997 (nur weiss) oder z.B. hier (lokaler Anbieter) http://www.schoenherr.de/product/9256919.html

Badges: Florian Gilcher (Ruby Berlin) sagte, er hätte ein Programm für das erstellen der Badges (und einen passenden Drucker), aber das klingt sonst auch nicht kompliziert.

- [ ] Enwurf für Lanyard-Bedruckung (Niklas?)
- [ ] Entwurf für Badge mit Namensfeld (Idealerweise beidseitige Namensschilder oder zwei-ender-lanyard)
- [ ] Ticket Rückseite: Sponsorenlogos
- [ ] Ticket Vorderseite: Name

**Comment by p0wl** [comment]
maybe ask jsunconf (@klyrr) if they have lanyards left (possible without jsunconf print, optimally 2 colors) that we may use in order to reduce waste.

@Farson will take care of this topic =)

**Comment by klyrr** [comment]
Wir haben die Lanyards nie bedrucken lassen. Wenn ihr noch warten könnt, kann ich euch das nach das JSUnconf sagen, wie viele wir übrig haben :)
Wir nehmen immer weiß und schwarz. Weiß für diejenigen, die nicht fotografiert werden wollen

**Comment by p0wl** [comment]
sehr cool. habt ihr vor eine Sammelstelle für lanyards die sonst weggeworfen würden am Sonntag aufzustellen?

**Comment by klyrr** [comment]
Erstellen der Lanyards machen wir bei den elbwerkstätten. Wir generieren ein pdf mit allen Badges und die drucken, falten und packen das in die Hüllen

**Comment by klyrr** [comment]
Sehr geile Idee!

**Comment by Farson** [comment]
ich würde gerne diese heir bestellen https://www.identmarket.de/schluesselbaender_messe-set_4040-203.htm

200 in Schwartz und 50 in Weis
Ausweishülle: DIN A6 Hochformat.

**Comment by Farson** [comment]
ne, wir lassen die jetzt doch bedrucken, das Kostet fast das selbe

ormal:
![normal](https://user-images.githubusercontent.com/1315067/38865821-4a5c9b0c-423f-11e8-9b78-9826dd97222e.png)


no photo: 
![no_photo](https://user-images.githubusercontent.com/1315067/38865818-458de266-423f-11e8-8805-4ec60262892c.png)

**Comment by klyrr** [comment]
wir hatten die Hüllen hier gekauft: 
https://www.lanyardstomorrow.co.uk/en/a6-vertical-large-id-badge-card-plastic-pocket-pouchs-17-5-x-11-8cm.html 
400 für 140GBP

**Comment by klyrr** [comment]
Und die Lanyards hier: https://www.werbeartikel-discount.com/product_info.php/products_id/119415

```
Lanyard Simple Lany - weiß | (17905806) | 300 | 81,30 €
Lanyard Simple Lany - schwarz | (17905803) | 400 | 108,40 €
```

**Comment by Farson** [comment]
danke Für den Tipp.

Dann würde ich diese heir bestellen: (da wir ja Lanyards mit 2 enden haben wollten, damit sich die Badges nicht immer drehen)
https://www.werbeartikel-discount.com/product_info.php/products_id/120593

**Comment by Farson** [comment]
Lanyards / Badges sind bestellt :heavy_check_mark:
