### ISSUE TITLE
Marketing Stickers

### ISSUE THREAD

**Issue by p0wl** [rughh/ruby-unconf#33]
* [x] design
* [x] printing via @halfbyte

**Comment by halfbyte** [comment]
Will close issue after I've fetched the stickers tomorrow.

**Comment by p0wl** [comment]
we have 75 now, should be enough to throw around before the event.

we will select some of the faces (https://gist.github.com/p0wl/b2232ce558659ab4370e619ce1cf43e9) to print in addition to more stickers.

**Comment by halfbyte** [comment]
@rughh/ruby-unconf-team I would want to go ahead ordering these stickers:

- Original UNC ONF
- Doggo (0,0)
- Käptn (2,0)
- Pirate (3,0)
- Headphones(1,2)

I wish we could print them all, but this seems to be a good subset and 5 different stickers makes for a good selection.

Any objections?

**Comment by halfbyte** [comment]
Habe Felix mal beauftragt, die Logos in Sticker zu überführen.
