### ISSUE TITLE
Voting Material

### ISSUE THREAD

**Issue by p0wl** [rughh/ruby-unconf#36]
* [x] Get Voting Points (jsunconf leftover?)
* [x] Print Contriboot Talks: https://contriboot.herokuapp.com/print.pdf
* [x] Print Empty Contriboot Slides (https://contriboot.herokuapp.com/print.pdf in empty, via @halfbyte)

**Comment by halfbyte** [comment]
@Farson I'll just generate an empty page at the end of the list so you can print it out a couple of times, that should be good enough, right?

**Comment by janz93** [comment]
@Farson as written in the chat on friday when selecting the different voting point to keep  in mind that there maybe are some colorblind people will be present.

**Comment by p0wl** [comment]
we will order different shapes
