### ISSUE TITLE
HAW Abstimmung

### ISSUE THREAD

**Issue by p0wl** [rughh/ruby-unconf#41]
* Desinfektionsmittel ist nicht vor Ort, müssen wir selber kaufen
* Seife, Papierhandtücher sind da, können wir selber nachfüllen
* Schlüsselübergabe Freitag 15 Uhr passt.
* Gender Neutral? Kann man machen
* Sponsorenlocations: Versuchen wir alle unten im Vorraum des Forums unterzubringen
* WLAN testen: Machen wir Freitag. Im Forum gibts für den Speaker nen Netzwerkkabel mit nem "direkten" Netzzungang
* Bildschirme/Laptop: Sind noch kaputt, es gibt irgendwie zwei Server PCs, sollte gehen, wenn die PCs bis dahin wieder funktionieren
* Lagerfläche könnten wir ab Mittwoch nutzen, müssen wir nur Frau Weichental schreiben
* Stellwände: 8x 190x100, 2x Flipchart (wenig Papier)
* Video Recording: Klären wir direkt mit den Studenten, ohne Frau Weichental
* Raucherbereich: Gibt keinen bestimmten, draußen stehen weniger Aschenbecher rum
* Freitag: Stühle werden im Forum für uns aufgebaut, ansonsten kommen wir an alles dran. 1-2 Tutoren werden auch vor Ort sein und helfen uns.
* Wenn wir Samstag die letzten sind sagen wir der Security Bescheid und schließen ab. Die Tutoren werden aber auch da sein.
* Schlüsselrückgabe: Über Tutoren oder Briefkasten wenn wir lange brauchen.

**Comment by halfbyte** [comment]
- Flipchart-Papier habe ich noch ziemlich viel rumliegen, kann ich was mitbringen. 
- Die Stellwände sind 100 breit? Das ist ein etwas komisches Maß, ggf. muss man da mal eine Schere ansetzen oder Papier umklappen. Das einfachste wäre vermutlich wenn jemand zum Büromarkt Hansen geht und sich eine Rechnung ausstellen lässt. Ansonsten: https://www.amazon.de/dp/B0091SZ2ZK/ref=twister_B0190LPIQK?_encoding=UTF8&psc=1
- Desinfektionsmittel sollte man bei der Metro bekommen. Amazon: https://www.amazon.de/Sterillium-H%C3%A4ndedesinfektion-500-mit-Horn-Dosierpumpe/dp/B01MTCR93G/ref=sr_1_2?ie=UTF8&qid=1524825583&sr=8-2&keywords=desinfektionsmittelspender

**Comment by halfbyte** [comment]
(Müsste vermutlich alles in andere Issues, mach ich noch mal.)
