### ISSUE TITLE
Last minute shopping list

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#48]
- table tennis racket and balls
- napkins
- ducktape
- toiletries (x6)
  - Tampons
  - Deo (M/F, Neutral)
  - Taschentücher
  - Sonnenmilch!
  - Desinfektion 2x
  - Einmalzahnbüsten?
  - Handcreme

**Comment by halfbyte** [comment]
@rughh/ruby-unconf-team I will probably head to Metro on Friday Afternoon-ish. Feel free to add more stuff to this list until then.
