### ISSUE TITLE
Create posting on Rubyflow

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#6]
Jan and Irina will discuss a posting there.

**Comment by sr189** [comment]
My draft here: https://docs.google.com/document/d/1oPnvF7kaayj6ocVjUZl6vcb6dNI9FRkPWMeq362WLfg/edit

**Comment by alster-wasser** [comment]
http://www.rubyflow.com/p/tmf47v-ruby-unconf-2018-hamburg-germany

Done
