### ISSUE TITLE
Diversity support stuff

### ISSUE THREAD

**Issue by halfbyte** [rughh/ruby-unconf#7]
Setting up the diversity scholarship means, probably:

- [x] Setting up the application form (see [JSUnconf2018's form for an example]
(https://docs.google.com/forms/d/e/1FAIpQLSeRwigM17MmKiT-
ARD82POmRbcyfv0JJPzQ1s40YRwfM5PQ0A/viewform)
- [x] Set up a deadline for application and add that and the link to the form to the website
- [x] Ask Tina or whoever is responsible this year for the process how JSUnconf processed and evaluated the applications

**Comment by halfbyte** [comment]
See https://goo.gl/forms/ewh8BYQHkyhtALc43

This is currently not in the shared folder because I want to protect the submitting persons, so if you want to be part of the diversity team, ping me and I'll share the form with you.

**Comment by halfbyte** [comment]
I've also included a deadline (18th of March for submission, 25th of March for confirmation) by simply calculating backwards from JSUnconf's dates and our conf date.

I'll also ping Tina to elaborate on the process for choosing candidates for the scholarship.

**Comment by halfbyte** [comment]
Okay, Diversity Form ist linked to from the Website.

No answer from Tina, will update this ticket with additional info as soon as I have it.

**Comment by p0wl** [comment]
we have some interested people, @halfbyte will take this topic and involve more people when he needs help. Thanks!

**Comment by halfbyte** [comment]
Decision by Committee: Mal mit 1500 EUR anfangen. Also 1500 PLUS Diversity Tickets
